apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo

	
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
containers:
      - name: mongo
        image: mongo:4.1
        ports:
        - containerPort: 27017
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: node-mongo-page-hit
spec:
  selector:
    app: node-mongo-page-hit
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800

	  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-page-hit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mongo-page-hit
  template:
    metadata:
      labels:
        app: node-mongo-page-hit
    spec:
      containers:
      - name: node-mongo-page-hit
        image: fresco/node-mongo-page-hit:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: PORT
          value: '8000'
